// import { Inter } from "next/font/google";
import "../styles/globals.css";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "weather App",
  openGraph: {
    description: "Generated by create next app",
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body style={{backgroundColor:'#e4eaf2'}}>{children}</body>
    </html>
  );
}
